MAKEFILE_PATH:=$(abspath $(lastword $(MAKEFILE_LIST)))
CURRENT_DIR:=$(abspath $(patsubst %/,%,$(dir $(MAKEFILE_PATH))))

SRCDIR=${CURRENT_DIR}/../src
BASEDIR?=${SRCDIR}
SDB_CFLAGS+=-I${SRCDIR} -I${BASEDIR} ${USER_CFLAGS}
SDB_LDFLAGS+=${BASEDIR}/libsdb.a ${USER_LDFLAGS}
SDB=${BASEDIR}/sdb
