all:
	#valabind --ctypes --module SimpleDB --vapidir ../vala --pkg sdb ../vala/sdb.vapi
	valabind --ctypes --module SimpleDB -l sdb ../vala/sdb.vapi
	#valabind --swig --module SimpleDB ../vala/sdb.vapi
