name: Coverity Scan
on:
  push:
    branches:
      - master

jobs:
  latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Determine current repository
        run: echo "{repo}={${GITHUB_REPOSITORY}}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v5
      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=sdb" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: mZuD8UEtISxYrTIc5K9Xjw

      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share

      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int make

      # TODO: Make it GitHub Action instead
      - name: Submit the result to Coverity Scan
        run: |
          tar czvf sdb.tgz cov-int
          curl \
            --form project=sdb \
            --form token=$TOKEN \
            --form email=noreply@radare.org \
            --form file=@sdb.tgz \
            --form version=trunk \
            --form description="sdb" \
            https://scan.coverity.com/builds?project=sdb
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
